[ENTESB-21273] Remove or refactor non-working quickstart spring-boot-camel-soap-rest-bridge
fabric8-quickstarts/spring-boot-camel-soap-rest-bridge pull request #32
Opened 2023-05-16 13:24 UTC by rnetuka

Issue: https://issues.redhat.com/browse/ENTESB-21273

A complete rehaul of the quickstart. It now features a (legacy) SOAP-based web service 
http://localhost:9090/service/bank-account
with two operations - _getBalance_ and _deposit_. The REST bridge is created on
http://localhost:8080/rest/bank-account
with similar operations - GET calls the _getBalance_ and POST (with plain text number value) calls the _deposit_ on the legacy service.

I intended the quickstart to be as simple as possible, thus removing SSO and 3scale. Also, I tried to unify it with other currently supported quickstarts by changing the pom.xml structure and adding Kubernetes integration test.

Any comments are welcome. The main challenges for me are 1. removing obsolete info from README.adoc 2. running the quickstart on Openshift (please try that, if you have the chance) and 3. changing the pom.xml. I'd be glad for an extra eye on those. Thanks.

2023-05-16 19:04 UTC, mcarlett requested changes
[deployment.yml#L16-L17](https://github.com/rnetuka/spring-boot-camel-soap-rest-bridge/blob/entesb-21273/src/main/jkube/deployment.yml#L16-L17) variable `JAVA_OPTIONS` is not resolved so the build fails, please remove those 2 lines if they are not necessary

JKube is unable to generate routes for services with multi ports, during the `oc:resource` goal the message is shown:

`oc: jkube-openshift-route: Not generating route for service spring-boot-camel-soap-rest-bridge as only single port services are supported. Has ports: [8080, 9090]`

and, without routes, it is impossible to call the rest/soap endpoints from outside the cluster.

A possible solution could be to split the default 1 service in 2 services ex:

a file soap-service.yml containing
```
spec:
  ports:
    - name: soap
      protocol: TCP
      port: 9090
      targetPort: 9090
```

and a file rest-service.yml containing
```
spec:
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
```

then both services will be exposed as routes.

If you want to reach only the rest endpoint from outside, you can keep the existing `service.yml` file with just `8080` port, the soap service is always available as `localhost` inside the pod

2023-05-16 19:04 UTC, mcarlett commented on src/main/resources/spring/camel-context.xml
> +                           host="localhost" port="8080"
`localhost` make the service unavailable from outside (via OCP route) so please change it with `{{server.address}}` that will be resolved as `0.0.0.0`

2023-05-17 09:26 UTC, rnetuka commented on src/main/resources/spring/camel-context.xml
> +                           host="localhost" port="8080"
Thanks Marco! I've made the changes.

2023-05-18 14:01 UTC, ffang approved these changes

2023-05-22 13:13 UTC, mcarlett approved these changes

2023-05-22 13:14 UTC, oscerd approved these changes

2023-05-22 13:14 UTC, merged